name: Validate Metadata

on:
  push:
    branches: [ main, dev, develop ]
  pull_request:
    branches: [ main, dev, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: Provenance-Aware-Metadata
          environment-file: environment.yml
          auto-activate-base: false

      - name: Build JSON-LD
        shell: bash -l {0}
        run: python src/build_metadata.py

      - name: Validate SHACL
        shell: bash -l {0}
        run: python src/validate_metadata.py

      - name: Run tests
        shell: bash -l {0}
        run: |
          pip install pytest
          pytest -q

      # Optional: smoke test FastAPI imports
      - name: Import API
        shell: bash -l {0}
        run: python -c "import importlib; importlib.import_module('fastapi'); importlib.import_module('uvicorn')"

